spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root

  application:
    name: USER-SERVICES
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: create-drop
server:
  port: 8082

eureka:
  instance:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      departmentService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      departmentService:
        maxAttempts: 3
        waitDuration: 5s
