spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: root

  application:
    name: USER-SERVICES
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

    hibernate:
      ddl-auto: create-drop
server:
  port: 8082

eureka:
  instance:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/